export const projects = [
  {
    id: 1,
    title: 'apro go',
    description: 'Social tool suggestion application',
    details: [],
    technologies: [
      'React',
      'Typescript',
      'Styled Components',
      'Netlify',
      'Storybook',
    ],
    img: '/projects/aprogo.png',
    githubUrl: 'https://github.com/team-ProD/FE-MAIN',
    websiteUrl: 'https://apro-go.netlify.app',
  },
  {
    id: 2,
    title: 'hipeak',
    description: 'Hipeak creative website',
    details: [],
    technologies: ['Gatsby', 'AWS'],
    img: '/projects/hipeak.png',
    githubUrl: null,
    websiteUrl: 'https://hipeak.co.nz',
  },
  {
    id: 3,
    title: 'caron',
    description: 'caron automotive website',
    details: [],
    technologies: ['Gatsby', 'AWS'],
    img: '/projects/caron.png',
    githubUrl: 'https://github.com/daniel0426/caron-automotive',
    websiteUrl: 'caron.co.nz',
  },
  {
    id: 4,
    title: 'netclix ',
    description: 'Netflix redesign project',
    details: [],
    technologies: ['Next.js', 'Typescript', 'Stripe', 'Firebase'],
    img: '/projects/netclix.png',
    githubUrl: 'https://github.com/daniel0426/netflix-clone',
    websiteUrl: 'https://netclix.vercel.app',
  },
  {
    id: 5,
    title: 'Noted',
    description: 'Personal note app',
    details: [],
    technologies: ['React', 'Redux (saga / thunk )', 'Material UI'],
    img: '/projects/noted.png',
    githubUrl: 'https://github.com/daniel0426/noteApp-redux-reduxThunk',
    websiteUrl: 'https://noted-personal.netlify.app',
  },
  {
    id: 6,
    title: 'Cryptoworld',
    description: 'Cryptocurrency information application',
    details: [],
    technologies: ['React', 'Redux (saga / thunk )', 'Material UI'],
    img: '/projects/noted.png',
    githubUrl: 'https://github.com/daniel0426/noteApp-redux-reduxThunk',
    websiteUrl: 'https://noted-personal.netlify.app',
  },
];
