export const projects = [
  {
    id: 1,
    title: 'apro go',
    description: 'Social tool suggestion application',
    details: [],
    technologies: [
      'React',
      'Typescript',
      'Styled Components',
      'Netlify',
      'Storybook',
    ],
    img: '/projects/aprogo.png',
    url: [
      { github: 'https://github.com/team-ProD/FE-MAIN' },
      { website: 'https://apro-go.netlify.app' },
    ],
  },
  {
    id: 2,
    title: 'hipeak',
    description: 'Hipeak creative website',
    details: [],
    technologies: ['Gatsby', 'AWS'],
    img: '/projects/hipeak.png',
    url: [{ github: undefined }, { website: 'https://hipeak.co.nz/' }],
  },
  {
    id: 3,
    title: 'caron',
    description: 'caron automotive website',
    details: [],
    technologies: ['Gatsby', 'AWS'],
    img: '/projects/caron.png',
    url: [
      { github: 'https://github.com/daniel0426/caron-automotive' },
      { website: 'caron.co.nz' },
    ],
  },
  {
    id: 4,
    title: 'netclix ',
    description: 'Netflix redesign project',
    details: [],
    technologies: ['Next.js', 'Typescript', 'Stripe', 'Firebase'],
    img: '/projects/netclix.png',
    url: [
      { github: 'https://github.com/daniel0426/netflix-clone' },
      { website: 'https://netclix.vercel.app/' },
    ],
  },
  {
    id: 5,
    title: 'Noted',
    description: 'Personal note app',
    details: [],
    technologies: ['React', 'Redux (saga / thunk )', 'Material UI'],
    img: '/projects/noted.png',
    url: [
      { github: 'https://github.com/daniel0426/noteApp-redux-reduxThunk' },
      { website: 'https://noted-personal.netlify.app' },
    ],
  },
];
